"""
Generate synthetic Cascade Bank Standard Operating Procedure (SOP) PDFs.

****************************************************************************
*  SYNTHETIC / FICTIONAL DEMO DATA — NOT A REAL BANK.                     *
*  Cascade Bank does not exist. All content here is generated by Faker    *
*  and templated text for a local RAG teaching demo.                      *
****************************************************************************

Each SOP has a fixed structure, in order:
    Title -> Purpose -> Scope -> Procedure Steps -> Roles & Responsibilities
    -> Revision History

Usage:
    from src.data_gen.generate_sops import generate_sops
    paths = generate_sops()          # uses cfg.corpus.num_sops
    paths = generate_sops(n=3)       # override count

Standalone:
    python -m src.data_gen.generate_sops
"""

from __future__ import annotations

import random
from datetime import datetime, timedelta
from pathlib import Path

from src.config import get_config
from src.data_gen.common import (
    CascadePDF,
    banking_paragraph,
    banking_sentence,
    ensure_dir,
    seed_all,
    slugify,
)

# ---------------------------------------------------------------------------
# SOP catalog
# ---------------------------------------------------------------------------

SOP_TOPICS = [
    "New Account Opening",
    "Suspicious Activity Reporting",
    "ATM Cash Replenishment",
    "Customer Dispute Resolution",
    "Wire Transfer Authorization",
    "Safe Deposit Box Access",
    "Fraud Alert Escalation",
    "Teller Cash Drawer Reconciliation",
    "Lost or Stolen Card Reporting",
    "Regulatory Examination Readiness",
]

ROLE_POOL = [
    ("Branch Manager", "Approves exceptions and oversees overall branch compliance with this SOP."),
    ("Teller", "Executes front-line steps and escalates anomalies to a supervisor."),
    ("Compliance Officer", "Reviews flagged cases and files required regulatory reports."),
    ("Customer Service Representative", "Communicates status and next steps to affected customers."),
    ("Operations Analyst", "Maintains process documentation and tracks completion metrics."),
    ("IT Security Team", "Supports system access, audit logging, and incident containment."),
    ("Risk Management", "Monitors control effectiveness and recommends process updates."),
    ("Regional Director", "Provides final sign-off on high-value or high-risk exceptions."),
]

STEP_ACTIONS = [
    "Verify the customer's identity using two forms of government-issued ID.",
    "Log the request in the core banking system with a timestamp.",
    "Confirm account ownership and current standing before proceeding.",
    "Escalate to a supervisor if the transaction exceeds the standard threshold.",
    "Document the interaction in the case management system.",
    "Notify the compliance team if any red flags are identified.",
    "Obtain secondary approval for any exception to standard limits.",
    "Update the customer record with the outcome of the request.",
    "Issue a written confirmation to the customer within one business day.",
    "Reconcile the transaction against the end-of-day ledger.",
    "Route the completed file to records management for retention.",
    "Perform a callback verification for high-risk requests.",
]


def _pick_topics(n: int) -> list[str]:
    if n <= len(SOP_TOPICS):
        return random.sample(SOP_TOPICS, n)
    picks = list(SOP_TOPICS)
    round_num = 2
    while len(picks) < n:
        for topic in SOP_TOPICS:
            if len(picks) >= n:
                break
            picks.append(f"{topic} (Regional Variant {round_num})")
        round_num += 1
    random.shuffle(picks)
    return picks[:n]


def _fake_revision_history(fake, sop_code: str) -> list[list[str]]:
    num_revisions = random.randint(3, 5)
    rows = []
    base_date = datetime.today() - timedelta(days=random.randint(400, 1200))
    version_major = 1
    for i in range(num_revisions):
        base_date += timedelta(days=random.randint(45, 200))
        version = f"v{version_major}.{i}"
        author = fake.name()
        description = random.choice(
            [
                "Initial draft.",
                "Updated procedure steps for new system.",
                "Clarified roles and responsibilities.",
                "Annual compliance review, minor edits.",
                "Incorporated regulator feedback.",
                "Updated thresholds and escalation contacts.",
            ]
        )
        rows.append([version, base_date.strftime("%Y-%m-%d"), author, description])
    return rows


def _build_sop_pdf(cfg, fake, topic: str, sop_number: int, path: Path) -> None:
    sop_code = f"SOP-{sop_number:03d}"
    title = f"SOP: {topic}"

    pdf = CascadePDF(company_name=cfg.corpus.company_name)
    pdf.set_disclaimed_metadata(title=title, subject="synthetic demo data")

    pdf.add_title_page(doc_title=title, subtitle=f"Standard Operating Procedure {sop_code}")

    # --- Purpose ---------------------------------------------------------
    pdf.add_section(
        "Purpose",
        [banking_paragraph(fake, min_sentences=2, max_sentences=4)],
        new_page=True,
    )

    # --- Scope -------------------------------------------------------------
    pdf.add_heading("Scope", new_page=False)
    pdf.add_paragraphs([banking_paragraph(fake, min_sentences=2, max_sentences=4)])

    # --- Procedure Steps -----------------------------------------------------
    pdf.add_heading("Procedure Steps", new_page=True)
    num_steps = random.randint(5, 10)
    steps = random.sample(STEP_ACTIONS, k=min(num_steps, len(STEP_ACTIONS)))
    while len(steps) < num_steps:
        steps.append(banking_sentence(fake))
    pdf.add_numbered_list(steps)

    # --- Roles & Responsibilities ------------------------------------------
    pdf.add_heading("Roles & Responsibilities", new_page=True)
    num_roles = random.randint(3, 5)
    roles = random.sample(ROLE_POOL, k=min(num_roles, len(ROLE_POOL)))
    pdf.add_key_value_table(roles, key_width=55)

    # --- Revision History ----------------------------------------------------
    pdf.add_heading("Revision History", new_page=True)
    rows = _fake_revision_history(fake, sop_code)
    pdf.add_simple_table(
        header=["Version", "Date", "Author", "Description"],
        rows=rows,
        col_widths=[20, 25, 45, 80],
    )

    ensure_dir(path.parent)
    pdf.output(str(path))


def generate_sops(n: int | None = None) -> list[Path]:
    """Generate synthetic Cascade Bank SOP PDFs.

    Reads defaults from config (`cfg.corpus.num_sops`, `cfg.paths.sops`,
    `cfg.corpus.seed`) unless overridden by `n`.

    Returns the list of written file paths.
    """
    cfg = get_config()
    fake = seed_all(cfg.corpus.seed)
    n = n if n is not None else cfg.corpus.num_sops

    out_dir = cfg.paths.sops
    ensure_dir(out_dir)

    topics = _pick_topics(n)

    written: list[Path] = []
    for i, topic in enumerate(topics, start=1):
        filename = f"{i:02d}_sop_{slugify(topic)}.pdf"
        path = out_dir / filename
        _build_sop_pdf(cfg, fake, topic, i, path)
        written.append(path)

    return written


if __name__ == "__main__":
    paths = generate_sops()
    print(f"Generated {len(paths)} SOP PDFs into {paths[0].parent if paths else '(none)'}")
    for p in paths:
        print(f"  {p}")
