"""
Generate the full synthetic Cascade Bank demo corpus (PDFs + SOPs + CSVs).

****************************************************************************
*  SYNTHETIC / FICTIONAL DEMO DATA — NOT A REAL BANK.                     *
*  Cascade Bank does not exist. Everything produced by this package is    *
*  generated by Faker / templated text for a local RAG teaching demo.     *
****************************************************************************

Usage:
    from src.data_gen.generate_all import generate_all
    generate_all()

Standalone (from project root):
    python -m src.data_gen.generate_all
"""

from __future__ import annotations

from src.config import get_config
from src.data_gen.generate_csvs import generate_csvs
from src.data_gen.generate_pdfs import generate_pdfs
from src.data_gen.generate_sops import generate_sops


def generate_all() -> dict[str, int]:
    """Generate PDFs, SOPs, and CSVs and print a summary.

    Returns a dict of {"pdfs": count, "sops": count, "csvs": count}.
    """
    cfg = get_config()

    print("=" * 70)
    print(f"Generating synthetic {cfg.corpus.company_name} demo corpus")
    print("SYNTHETIC / FICTIONAL DEMO DATA - NOT A REAL BANK")
    print("=" * 70)

    pdf_paths = generate_pdfs()
    print(f"[pdfs] wrote {len(pdf_paths)} files -> {cfg.paths.pdfs}")

    sop_paths = generate_sops()
    print(f"[sops] wrote {len(sop_paths)} files -> {cfg.paths.sops}")

    csv_paths = generate_csvs()
    print(f"[csvs] wrote {len(csv_paths)} files -> {cfg.paths.csvs}")

    summary = {
        "pdfs": len(pdf_paths),
        "sops": len(sop_paths),
        "csvs": len(csv_paths),
    }

    print("-" * 70)
    print("Summary:")
    for key, count in summary.items():
        print(f"  {key}: {count}")
    total = sum(summary.values())
    print(f"  total files: {total}")
    print("=" * 70)

    return summary


if __name__ == "__main__":
    generate_all()
