"""
Generate synthetic Cascade Bank policy documents and product manuals as PDFs.

****************************************************************************
*  SYNTHETIC / FICTIONAL DEMO DATA — NOT A REAL BANK.                     *
*  Cascade Bank does not exist. All content here is generated by Faker    *
*  and templated text for a local RAG teaching demo.                      *
****************************************************************************

Usage:
    from src.data_gen.generate_pdfs import generate_pdfs
    paths = generate_pdfs()          # uses cfg.corpus.num_pdfs
    paths = generate_pdfs(n=5)       # override count

Standalone:
    python -m src.data_gen.generate_pdfs
"""

from __future__ import annotations

import random
from pathlib import Path

from src.config import get_config
from src.data_gen.common import (
    CascadePDF,
    banking_paragraph,
    ensure_dir,
    seed_all,
    slugify,
)

# ---------------------------------------------------------------------------
# Document catalog
# ---------------------------------------------------------------------------

POLICY_TITLES = [
    "Account Overdraft Policy",
    "Wire Transfer Policy",
    "KYC/AML Compliance Policy",
    "Data Privacy Policy",
    "Loan Origination Policy",
    "Foreign Currency Exchange Policy",
    "ATM Card Policy",
    "Identity Theft Protection Policy",
    "Regulation E Error Resolution Policy",
    "Credit Card Rewards Policy",
]

MANUAL_TITLES = [
    "Cascade Checking Account User Guide",
    "Mobile Banking App Manual",
    "Business Credit Card Manual",
    "Online Bill Pay User Guide",
    "Certificate of Deposit Product Guide",
    "Small Business Banking Manual",
    "Home Equity Line of Credit Manual",
    "Savings Account User Guide",
]

POLICY_SECTIONS = [
    "Purpose",
    "Scope",
    "Policy Statement",
    "Procedures",
    "Roles and Responsibilities",
    "Exceptions and Escalation",
    "Related Regulations",
]

MANUAL_SECTIONS = [
    "Overview",
    "Getting Started",
    "Key Features",
    "Step-by-Step Instructions",
    "Fees and Limits",
    "Troubleshooting and FAQ",
    "Contacting Support",
]


def _doc_catalog() -> list[tuple[str, str]]:
    """All (title, doc_type) pairs this generator knows about."""
    return [(t, "policy") for t in POLICY_TITLES] + [(t, "manual") for t in MANUAL_TITLES]


def _pick_titles(n: int) -> list[tuple[str, str]]:
    """Pick `n` (title, doc_type) pairs, reusing/varying the catalog if n
    exceeds its size so filenames stay distinct."""
    catalog = _doc_catalog()
    if n <= len(catalog):
        return random.sample(catalog, n)

    picks: list[tuple[str, str]] = list(catalog)
    round_num = 2
    while len(picks) < n:
        for title, doc_type in catalog:
            if len(picks) >= n:
                break
            picks.append((f"{title} (Supplement {round_num})", doc_type))
        round_num += 1
    random.shuffle(picks)
    return picks[:n]


def _build_pdf(cfg, fake, title: str, doc_type: str, path: Path) -> None:
    pdf = CascadePDF(company_name=cfg.corpus.company_name)
    pdf.set_disclaimed_metadata(title=title, subject="synthetic demo data")

    subtitle = "Internal Policy Document" if doc_type == "policy" else "Product User Manual"
    pdf.add_title_page(doc_title=title, subtitle=subtitle)

    section_pool = POLICY_SECTIONS if doc_type == "policy" else MANUAL_SECTIONS
    num_sections = random.randint(2, 4)
    headings = random.sample(section_pool, k=min(num_sections, len(section_pool)))

    for heading in headings:
        # Vary paragraph counts so overall chunk counts vary across the corpus.
        num_paragraphs = random.randint(4, 12)
        paragraphs = [
            banking_paragraph(fake, min_sentences=3, max_sentences=8)
            for _ in range(num_paragraphs)
        ]
        pdf.add_section(heading, paragraphs, new_page=True)

    ensure_dir(path.parent)
    pdf.output(str(path))


def generate_pdfs(n: int | None = None) -> list[Path]:
    """Generate synthetic Cascade Bank policy / manual PDFs.

    Reads defaults from config (`cfg.corpus.num_pdfs`, `cfg.paths.pdfs`,
    `cfg.corpus.seed`) unless overridden by `n`.

    Returns the list of written file paths.
    """
    cfg = get_config()
    fake = seed_all(cfg.corpus.seed)
    n = n if n is not None else cfg.corpus.num_pdfs

    out_dir = cfg.paths.pdfs
    ensure_dir(out_dir)

    docs = _pick_titles(n)

    written: list[Path] = []
    for i, (title, doc_type) in enumerate(docs, start=1):
        filename = f"{i:02d}_{doc_type}_{slugify(title)}.pdf"
        path = out_dir / filename
        _build_pdf(cfg, fake, title, doc_type, path)
        written.append(path)

    return written


if __name__ == "__main__":
    paths = generate_pdfs()
    print(f"Generated {len(paths)} PDFs into {paths[0].parent if paths else '(none)'}")
    for p in paths:
        print(f"  {p}")
