"""
Generate synthetic Cascade Bank operational CSVs.

****************************************************************************
*  SYNTHETIC / FICTIONAL DEMO DATA — NOT A REAL BANK.                     *
*  Cascade Bank does not exist. All rows below are generated by Faker     *
*  for a local RAG teaching demo. No real customers, employees, or        *
*  transactions are represented.                                          *
****************************************************************************

Produces five CSVs with distinct schemas:
    employee_directory.csv, transaction_log.csv, support_tickets.csv,
    branch_inventory.csv, loan_portfolio.csv

A shared `DISCLAIMER.txt` is written alongside them (CSV rows themselves
stay schema-clean, with no injected disclaimer column).

Usage:
    from src.data_gen.generate_csvs import generate_csvs
    paths = generate_csvs()          # uses cfg.corpus.num_csvs
    paths = generate_csvs(n=3)       # override count (first n schemas)

Standalone:
    python -m src.data_gen.generate_csvs
"""

from __future__ import annotations

import random
from pathlib import Path

import pandas as pd

from src.config import get_config
from src.data_gen.common import DISCLAIMER, DISCLAIMER_LONG, ensure_dir, seed_all

# ---------------------------------------------------------------------------
# Shared reference data
# ---------------------------------------------------------------------------

EMPLOYEE_ROLES = [
    "Teller", "Branch Manager", "Loan Officer", "Compliance Analyst",
    "Customer Service Representative", "IT Support Specialist",
    "Financial Advisor", "Operations Manager", "Risk Analyst",
    "Marketing Specialist", "Head Teller", "Assistant Branch Manager",
]

DEPARTMENTS = [
    "Retail Banking", "Commercial Banking", "Compliance", "Information Technology",
    "Risk Management", "Operations", "Marketing", "Human Resources", "Treasury",
]

TXN_TYPES = ["deposit", "withdrawal", "transfer", "fee"]
TXN_CHANNELS = ["branch", "atm", "mobile", "online", "phone"]
TXN_STATUSES = ["completed", "pending", "failed", "reversed"]

TICKET_CATEGORIES = [
    "Account Access", "Card Issue", "Loan Inquiry", "Dispute",
    "Mobile App Bug", "Fraud Report", "Fee Inquiry", "Other",
]
TICKET_PRIORITIES = ["Low", "Medium", "High", "Urgent"]
TICKET_STATUSES = ["Open", "In Progress", "Resolved", "Closed"]

LOAN_TYPES = ["Mortgage", "Auto Loan", "Personal Loan", "Business Loan", "HELOC", "Student Loan"]
LOAN_STATUSES = ["Current", "Delinquent", "Paid Off", "Charged Off", "In Review"]


def _branch_names(fake, count: int) -> list[str]:
    return [f"{fake.city()} Branch" for _ in range(count)]


# ---------------------------------------------------------------------------
# Individual schema builders
# ---------------------------------------------------------------------------


def _employee_directory(fake, out_dir: Path) -> Path:
    n = random.randint(30, 60)
    branches = _branch_names(fake, random.randint(6, 12))
    rows = []
    for i in range(1, n + 1):
        name = fake.name()
        rows.append(
            {
                "employee_id": f"EMP{i:05d}",
                "name": name,
                "role": random.choice(EMPLOYEE_ROLES),
                "department": random.choice(DEPARTMENTS),
                "branch": random.choice(branches),
                "email": fake.unique.user_name() + "@cascadebank-demo.example",
                "hire_date": fake.date_between(start_date="-12y", end_date="today").isoformat(),
            }
        )
    df = pd.DataFrame(rows)
    path = out_dir / "employee_directory.csv"
    df.to_csv(path, index=False)
    return path


def _transaction_log(fake, out_dir: Path) -> Path:
    n = random.randint(200, 350)
    rows = []
    for i in range(1, n + 1):
        txn_type = random.choice(TXN_TYPES)
        amount = round(random.uniform(2.5, 15000), 2)
        if txn_type == "fee":
            amount = round(random.uniform(1, 75), 2)
        rows.append(
            {
                "txn_id": f"TXN{i:07d}",
                "date": fake.date_between(start_date="-2y", end_date="today").isoformat(),
                "account_id": f"ACC{random.randint(100000, 999999)}",
                "type": txn_type,
                "amount": amount,
                "channel": random.choice(TXN_CHANNELS),
                "status": random.choices(
                    TXN_STATUSES, weights=[0.85, 0.07, 0.05, 0.03], k=1
                )[0],
            }
        )
    df = pd.DataFrame(rows)
    path = out_dir / "transaction_log.csv"
    df.to_csv(path, index=False)
    return path


def _support_tickets(fake, out_dir: Path) -> Path:
    n = random.randint(80, 150)
    summary_templates = [
        "Customer reported an issue with {category_lower} and requested follow-up.",
        "Inbound call regarding {category_lower}; agent gathered details for review.",
        "Customer submitted a request related to {category_lower} via the mobile app.",
        "Branch staff escalated a {category_lower} case for further investigation.",
        "Customer disputes a recent charge tied to {category_lower}.",
    ]
    rows = []
    for i in range(1, n + 1):
        category = random.choice(TICKET_CATEGORIES)
        summary = random.choice(summary_templates).format(category_lower=category.lower())
        rows.append(
            {
                "ticket_id": f"TCK{i:06d}",
                "opened_date": fake.date_between(start_date="-1y", end_date="today").isoformat(),
                "customer_name": fake.name(),
                "category": category,
                "priority": random.choice(TICKET_PRIORITIES),
                "status": random.choice(TICKET_STATUSES),
                "summary": summary,
            }
        )
    df = pd.DataFrame(rows)
    path = out_dir / "support_tickets.csv"
    df.to_csv(path, index=False)
    return path


def _branch_inventory(fake, out_dir: Path) -> Path:
    n = random.randint(20, 35)
    rows = []
    for i in range(1, n + 1):
        city = fake.city()
        rows.append(
            {
                "branch_id": f"BR{i:04d}",
                "branch_name": f"{city} Branch",
                "city": city,
                "atm_count": random.randint(1, 6),
                "safe_deposit_boxes": random.randint(0, 400),
                "staff_count": random.randint(4, 40),
            }
        )
    df = pd.DataFrame(rows)
    path = out_dir / "branch_inventory.csv"
    df.to_csv(path, index=False)
    return path


def _loan_portfolio(fake, out_dir: Path) -> Path:
    n = random.randint(100, 200)
    rows = []
    for i in range(1, n + 1):
        loan_type = random.choice(LOAN_TYPES)
        if loan_type == "Mortgage":
            principal = round(random.uniform(80000, 750000), 2)
            term_months = random.choice([180, 240, 360])
            rate = round(random.uniform(3.0, 7.5), 3)
        elif loan_type == "Auto Loan":
            principal = round(random.uniform(8000, 60000), 2)
            term_months = random.choice([36, 48, 60, 72])
            rate = round(random.uniform(3.5, 9.5), 3)
        elif loan_type == "HELOC":
            principal = round(random.uniform(10000, 150000), 2)
            term_months = random.choice([60, 120, 180])
            rate = round(random.uniform(4.0, 9.0), 3)
        elif loan_type == "Business Loan":
            principal = round(random.uniform(15000, 500000), 2)
            term_months = random.choice([24, 36, 60, 84, 120])
            rate = round(random.uniform(5.0, 11.0), 3)
        elif loan_type == "Student Loan":
            principal = round(random.uniform(5000, 100000), 2)
            term_months = random.choice([120, 180, 240])
            rate = round(random.uniform(3.0, 8.0), 3)
        else:  # Personal Loan
            principal = round(random.uniform(1000, 35000), 2)
            term_months = random.choice([12, 24, 36, 48, 60])
            rate = round(random.uniform(6.0, 15.0), 3)

        rows.append(
            {
                "loan_id": f"LN{i:06d}",
                "customer_name": fake.name(),
                "loan_type": loan_type,
                "principal": principal,
                "interest_rate": rate,
                "term_months": term_months,
                "status": random.choices(
                    LOAN_STATUSES, weights=[0.65, 0.1, 0.15, 0.03, 0.07], k=1
                )[0],
            }
        )
    df = pd.DataFrame(rows)
    path = out_dir / "loan_portfolio.csv"
    df.to_csv(path, index=False)
    return path


_SCHEMA_BUILDERS = [
    _employee_directory,
    _transaction_log,
    _support_tickets,
    _branch_inventory,
    _loan_portfolio,
]


def _write_disclaimer(out_dir: Path) -> None:
    disclaimer_path = out_dir / "DISCLAIMER.txt"
    disclaimer_path.write_text(
        f"{DISCLAIMER}\n\n{DISCLAIMER_LONG}\n\n"
        "This applies to every CSV file in this directory: employee_directory.csv, "
        "transaction_log.csv, support_tickets.csv, branch_inventory.csv, and "
        "loan_portfolio.csv. All rows are generated by Faker and do not represent "
        "real people, accounts, or transactions.\n",
        encoding="utf-8",
    )


def generate_csvs(n: int | None = None) -> list[Path]:
    """Generate synthetic Cascade Bank operational CSVs.

    Reads defaults from config (`cfg.corpus.num_csvs`, `cfg.paths.csvs`,
    `cfg.corpus.seed`) unless overridden by `n`. `n` selects how many of the
    five distinct schemas to build (in the fixed order defined above); values
    above 5 are clamped to 5 since each schema is generated at most once per
    run.

    Also writes a shared `DISCLAIMER.txt` into the output directory.

    Returns the list of written file paths.
    """
    cfg = get_config()
    fake = seed_all(cfg.corpus.seed)
    n = n if n is not None else cfg.corpus.num_csvs
    n = max(0, min(n, len(_SCHEMA_BUILDERS)))

    out_dir = cfg.paths.csvs
    ensure_dir(out_dir)

    written: list[Path] = []
    for builder in _SCHEMA_BUILDERS[:n]:
        path = builder(fake, out_dir)
        written.append(path)

    if written:
        _write_disclaimer(out_dir)

    return written


if __name__ == "__main__":
    paths = generate_csvs()
    print(f"Generated {len(paths)} CSVs into {paths[0].parent if paths else '(none)'}")
    for p in paths:
        print(f"  {p}")
